# Generated by Django 3.2.3 on 2021-09-08 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('upfront_commission_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('trial_commission_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
