# Generated by Django 3.2.3 on 2021-09-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_lenders', '0002_rename_lenders_lender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='active',
            field=models.BooleanField(db_index=True),
        ),
    ]
